name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Prepare static site
        run: |
          mkdir -p public
          
          # Convert template to static HTML
          python3 -c "
import re

def convert_template(input_file, output_file):
    with open(input_file, 'r') as f:
        content = f.read()
    
    # Remove Jinja2 block tags
    content = re.sub(r'{%\s*\w+\s*.*?%}', '', content)
    
    # Replace url_for with static paths
    content = re.sub(r'{{ url_for\(\'static\', filename=\'(.*?)\'\) }}', r'static/\1', content)
    
    # Replace problematic image paths
    content = re.sub(r'url\(\'static/images/(.*?)\'\)', r'url(\"static/images/\1\")', content)
    
    # Remove any remaining Jinja2 variable tags
    content = re.sub(r'{{.*?}}', '', content)
    
    with open(output_file, 'w') as f:
        f.write(content)

convert_template('templates/index.html', 'public/index.html')
"
          
          # Ensure static directories exist
          mkdir -p public/static/css
          mkdir -p public/static/js
          mkdir -p public/static/images

          # Copy static files
          cp -r static/css/* public/static/css/ || true
          cp -r static/js/* public/static/js/ || true
          cp -r static/images/* public/static/images/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
