name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare static site
        run: |
          mkdir -p public/static/css
          mkdir -p public/static/js
          mkdir -p public/static/images

          # Replace Jinja2 URL references with static paths
          sed 's|{{ url_for('\''static'\'', filename='\''\([^'\'']*\)'\'')|"static/\1"|g' templates/index.html > public/index.html

          # Copy static files
          cp -r static/css/* public/static/css/ || true
          cp -r static/js/* public/static/js/ || true
          cp -r static/images/* public/static/images/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
